
from ultralytics import YOLO
import os
import matplotlib.pyplot as plt

def evaluate_model():
    print("Evaluating Model...")
    model_path = os.path.join("models", "yolo_best", "weights", "best.pt")
    if not os.path.exists(model_path):
        print("Model not found, using pretrained yolov8n.pt")
        model = YOLO("yolov8n.pt")
    else:
        model = YOLO(model_path)
    
    # Run validation
    metrics = model.val()
    
    print(f"mAP@50: {metrics.box.map50}")
    print(f"mAP@50-95: {metrics.box.map}")
    print(f"Precision: {metrics.box.mp}")
    print(f"Recall: {metrics.box.mr}")
    
    # Confusion Matrix is auto-generated by YOLO in runs/detect/val/confusion_matrix.png
    # We can just point the user there.
    print(f"Plots saved to {metrics.save_dir}")

if __name__ == "__main__":
    evaluate_model()
